### ISSUE TITLE
Two errors when trying to build.

### ISSUE THREAD

**Issue by hackerncoder** [numericube/lektor-i18n-plugin#21]
I have no idea, here is the full output.

```python
Started build
  Tree: /var/www/torproject/tpo-source
  Output path: /var/www/torproject/tpo
i18n activated, with main language en
Parsing templates for i18n into ../../../../tmp/templates.pot
extracting messages from lego/templates/404.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_")
[...]
extracting messages from templates/macros/topic.html (encoding="utf-8", extensions="jinja2.ext.autoescape,jinja2.ext.with_")
writing PO template file to /tmp/templates.pot
/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/pluginsystem.py:175: DeprecationWarning: The plugin "i18n" function "on_before_build" does not accept extra_flags. It should be updated to accept `**extra` so that it will not break if new parameters are passed to it by newer versions of Lektor.
  "versions of Lektor.".format(plugin.id, funcname), DeprecationWarning
U ca/index.html
  E ca/index.html (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 2: unexpected end of data)
    Traceback (most recent call last):
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 800, in update
        yield ctx
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 1070, in build_artifact
        build_func(artifact)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/build_programs.py", line 183, in build_artifact
        self.source['_template'], this=self.source)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 655, in render_template_into
        this=this, **extra)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/environment.py", line 542, in render_template
        return self.jinja_env.get_or_select_template(name).render(ctx)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/var/www/torproject/tpo-source/templates/jumbotron.html", line 1, in top-level template code
        {% extends "homepage.html" %}
      File "/var/www/torproject/tpo-source/templates/homepage.html", line 1, in top-level template code
        {% include 'meta.html' %}
      File "/var/www/torproject/tpo-source/templates/meta.html", line 5, in top-level template code
        <meta name="description" content="{{ _('Defend yourself against tracking and surveillance. Circumvent censorship.') }} | {{ this.title }}">
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/ext.py", line 144, in _gettext_alias
        return __context.call(__context.resolve("gettext"), *args, **kwargs)
      File "/var/www/torproject/tpo-source/lego/packages/i18n/lektor_i18n.py", line 89, in gettext
        self.init_translator() # lagnuage could have changed
      File "/var/www/torproject/tpo-source/lego/packages/i18n/lektor_i18n.py", line 86, in init_translator
        languages=[ctx.locale], fallback=True)
      File "/usr/lib/python3.7/gettext.py", line 548, in translation
        t = _translations.setdefault(key, class_(fp))
      File "/usr/lib/python3.7/gettext.py", line 260, in __init__
        self._parse(fp)
      File "/usr/lib/python3.7/gettext.py", line 421, in _parse
        catalog[str(msg, charset)] = str(tmsg, charset)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 2: unexpected end of data
/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/pluginsystem.py:175: DeprecationWarning: The plugin "i18n" function "on_after_build" does not accept extra_flags. It should be updated to accept `**extra` so that it will not break if new parameters are passed to it by newer versions of Lektor.
  "versions of Lektor.".format(plugin.id, funcname), DeprecationWarning
U de/index.html
  E de/index.html (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte)
    Traceback (most recent call last):
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 800, in update
        yield ctx
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 1070, in build_artifact
        build_func(artifact)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/build_programs.py", line 183, in build_artifact
        self.source['_template'], this=self.source)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 655, in render_template_into
        this=this, **extra)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/environment.py", line 542, in render_template
        return self.jinja_env.get_or_select_template(name).render(ctx)
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/var/www/torproject/tpo-source/templates/jumbotron.html", line 1, in top-level template code
        {% extends "homepage.html" %}
      File "/var/www/torproject/tpo-source/templates/homepage.html", line 1, in top-level template code
        {% include 'meta.html' %}
      File "/var/www/torproject/tpo-source/templates/meta.html", line 5, in top-level template code
        <meta name="description" content="{{ _('Defend yourself against tracking and surveillance. Circumvent censorship.') }} | {{ this.title }}">
      File "/usr/local/lib/lektor/lib/python3.7/site-packages/jinja2/ext.py", line 144, in _gettext_alias
        return __context.call(__context.resolve("gettext"), *args, **kwargs)
      File "/var/www/torproject/tpo-source/lego/packages/i18n/lektor_i18n.py", line 89, in gettext
        self.init_translator() # lagnuage could have changed
      File "/var/www/torproject/tpo-source/lego/packages/i18n/lektor_i18n.py", line 86, in init_translator
        languages=[ctx.locale], fallback=True)
      File "/usr/lib/python3.7/gettext.py", line 548, in translation
        t = _translations.setdefault(key, class_(fp))
      File "/usr/lib/python3.7/gettext.py", line 260, in __init__
        self._parse(fp)
      File "/usr/lib/python3.7/gettext.py", line 421, in _parse
        catalog[str(msg, charset)] = str(tmsg, charset)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Finished build in 1.54 sec
Traceback (most recent call last):
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/pluginsystem.py", line 166, in emit
    rv[plugin.id] = handler(**kwargs)
TypeError: on_before_build() got an unexpected keyword argument 'extra_flags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lektor", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/cli.py", line 632, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/cli.py", line 241, in build_cmd
    success = _build()
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/cli.py", line 234, in _build
    failures = builder.build_all()
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 1141, in build_all
    prog, build_state = self.build(source, path_cache=path_cache)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/builder.py", line 1110, in build
    source=source, prog=prog)
  File "/usr/local/lib/lektor/lib/python3.7/site-packages/lektor/pluginsystem.py", line 170, in emit
    rv[plugin.id] = handler(**old_style_kwargs)
  File "/var/www/torproject/tpo-source/lego/packages/i18n/lektor_i18n.py", line 342, in on_before_build
    join(self.i18npath,'_compiled'), languages=[language], fallback = True)
  File "/usr/lib/python3.7/gettext.py", line 548, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib/python3.7/gettext.py", line 260, in __init__
    self._parse(fp)
  File "/usr/lib/python3.7/gettext.py", line 421, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 2: unexpected end of data
```
